export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAILURE = 'BOOKING_CREATE_FAILURE';
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET';

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAILURE = 'BOOKING_DETAILS_FAILURE';

export const BOOKING_PAY_REQUEST = 'BOOKING_PAY_REQUEST';
export const BOOKING_PAY_SUCCESS = 'BOOKING_PAY_SUCCESS';
export const BOOKING_PAY_FAILURE = 'BOOKING_PAY_FAILURE';
export const BOOKING_PAY_RESET = 'BOOKING_PAY_RESET';

export const BOOKING_MINE_LIST_REQUEST = 'BOOKING_MINE_LIST_REQUEST';
export const BOOKING_MINE_LIST_SUCCESS = 'BOOKING_MINE_LIST_SUCCESS';
export const BOOKING_MINE_LIST_FAILURE = 'BOOKING_MINE_LIST_FAILURE';

export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST';
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS';
export const BOOKING_LIST_FAILURE = 'BOOKING_LIST_FAILURE';

export const BOOKING_DELETE_REQUEST = 'BOOKING_DELETE_REQUEST';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';
export const BOOKING_DELETE_FAILURE = 'BOOKING_DELETE_FAILURE';
export const BOOKING_DELETE_RESET = 'BOOKING_DELETE_RESET';