export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAILURE = 'BOOKING_CREATE_FAILURE';
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET';

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAILURE = 'BOOKING_DETAILS_FAILURE';
